#! /bin/sh
set -e

#	Compile all files
#find /usr/lib/vault/python/vault -name "*.py" -print0 | xargs -0 -n 1 python -m compileall 

#	Update documentation indexes
if which scrollkeeper-update > /dev/null; then
        scrollkeeper-update
fi

#compile language files with msgfmt
#olddir=`pwd`
#cd /usr/lib/python/python/vault
#	Find and compile all language files#
#for po in `find i18n -name "*.po" -print`; do#
#	mo=`echo $po | sed "s/po$/mo/"`
#	msgfmt $po --output-file $mo
#done
#cd $olddir

#	python-poster is not yet available. So the easist thing to
#	do is ensure python-setuptools is included, and then 
#	use easy_install to add poster.
easy_install poster

