#! /bin/sh
set -e

#	Compile all files
find /usr/lib/python2.7/dist-packages/vault -name "*.py" -print0 | xargs -0 -n 1 python -m compileall 

#	Update documentation indexes
if which scrollkeeper-update > /dev/null; then
        scrollkeeper-update
fi

#compile language files with msgfmt
olddir=`pwd`
cd /usr/lib/python2.7/dist-packages/vault
#	Find and compile all language files
for po in `find i18n -name "*.po" -print`; do
	mo=`echo $po | sed "s/po$/mo/"`
	msgfmt $po --output-file $mo
done
cd $olddir

#	For some reason, deb file creation does not include 
#	python package requirements. So we manually add them
#	in. Note, I've added python-setuptools so easy_install is here
easy_install poster
easy_install boto

#if [ "$1" = "triggered" ]; then
#    update-python-modules --post-install
#    exit 0
#fi
#
## Remove the old directory.
#if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 0.90; then
#    rm -rf /var/lib/python-support
#fi
#
#if ! [ -e /var/lib/python-support ]; then
#    ln -sf /usr/lib/pymodules /var/lib/python-support
#fi
#
#DEBHELPER#

#update-python-modules --post-install python-support.private
