#! /bin/sh
set -e

#DEBHELPER#

# Don't fail if this command fails, it's not important enough.
# In this case, make the cleanup by hand.
#update-python-modules -c -b python-support.private || \

rm -f /usr/share/vault/*.pyc /usr/share/vault/*/*.pyc

#	Clear out all the compiled language files
rm -f/usr/lib/python2.7/dist-packages/vault/i18n/*/*/*.mo
