#! /bin/sh
set -e

#DEBHELPER#

# Don't fail if this command fails, it's not important enough.
# In this case, make the cleanup by hand.
#update-python-modules -c -b python-support.private || \

rm -f /usr/lib/vault/vault/*.pyc //usr/lib/vault/vault/*/*.pyc

#	Clear out all the compiled language files
rm -f/usr/lib/vault/vault/i18n/*/*/*.mo
